title: Herman's Hole
email: inbox@hermanshole.com
description: The abyss of some netsec info.
baseurl: ""
url: "http://hermanshole.com"
show_downloads: false
google_analytics: UA-86131644-1
permalink: /blog/:title.html

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
gems:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
